workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
      vars:
        JAVA_HOME: /usr/libexec/java_home -v 17
    triggering:
      events:
        - push
    scripts:
      - name: Set Java 17
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
      - name: Build App Bundle
        script: flutter build appbundle --debug
    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
      - build/app/outputs/bundle/debug/app-debug.aab
